apiVersion: v1
kind: Service
metadata:
  name: lensagents-nginx-demo
  labels: { app: lensagents-nginx-demo }
spec:
  selector: { app: lensagents-nginx-demo }
  ports:
    - port: 80
      targetPort: 80
